/**
 * User-facing copy for the dsh-android cards and panel (en/zh, like the host).
 *
 * `AndroidCopy` is derived from the ENGLISH table, so a key missing from the
 * Chinese table is a compile error (the dsh-ios pattern, kept verbatim).
 * Every `err*` key maps 1:1 to an `AndroidRouteErrorCode` the host routes
 * report — see ROUTE_ERROR_COPY_KEYS in protocol.ts.
 */

export type AndroidLocale = 'en' | 'zh'

const COPY = {
  en: {
    android: 'Android',
    actionBoot: 'Start',
    actionScreenshot: 'Screenshot',
    actionInteract: 'Interact',
    actionBuildRun: 'Build & Run',
    booting: 'Starting the device stream…',
    connecting: 'Connecting to the live stream…',
    connectingScreenshot: 'Loading screenshot…',
    live: 'live',
    unavailable: 'unavailable',
    done: 'done',
    streamUnavailable: 'stream not available',
    screenshotUnavailable: 'screenshot not available',
    retry: 'Retry',
    refresh: 'Refresh',
    // Android navigation bar: ◁ ○ □ — three peers, no double-click semantics.
    back: 'Back',
    home: 'Home',
    recents: 'Recents',
    deviceMenu: 'Device actions',
    deviceNotifications: 'Notifications',
    deviceQuickSettings: 'Quick Settings',
    deviceLock: 'Lock screen',
    deviceWake: 'Wake',
    deviceAssistant: 'Assistant',
    deviceActionFailed: 'the device action failed',
    screenshot: 'Screenshot',
    captured: 'Captured',
    capturing: 'Capturing…',
    rotate: 'Rotate',
    toolbar: 'Device toolbar',
    sizeMode: 'Device display size',
    frameStyle: 'Device frame style',
    frameStyleNone: 'Frameless',
    frameStyleBezel: 'Bezel',
    frameStyleDevice: 'Phone frame',
    sizeQuickFit: 'Fit to panel width',
    sizeQuickPercent100: 'Display at 100%',
    sizeQuickS: 'Small size (S, 240px)',
    sizeQuickM: 'Medium size (M, 320px)',
    streamAlt: 'Live Android device — click to tap, drag to gesture',
    screenshotAlt: 'Android device screenshot',
    captureScreenshot: 'Capturing screenshot…',
    interacting: 'Interacting with the device…',
    building: 'Building and installing the app…',
    noPreview: 'No live view is available for this result.',
    toolFailed: 'The tool call failed.',
    openApk: 'Open APK',
    openScreenshot: 'Open screenshot',
    packageName: 'Package',
    device: 'device',
    offline: 'Offline',
    panelLive: 'Live',
    closePanel: 'Close device panel',
    resizePanel: 'Drag to resize the device panel',
    openInPanel: 'Open in sidebar',
    openAndroidPanel: 'Open device panel',
    devicePicker: 'Android device',
    deviceSwitching: 'Switching…',
    deviceStreaming: 'live',
    deviceOnline: 'online',
    deviceEmulators: 'Emulators',
    devicePhysical: 'Phones',
    deviceAvds: 'Available AVDs',
    deviceAvdHint: 'start it with android_boot',
    deviceNone: 'No device connected',
    // Auto-follow indicator (the panel follows the agent's newest target).
    followActive: 'Auto-follow',
    followHint: 'The panel follows the agent’s newest target device',
    followResume: 'Resume following',
    switchFailed: 'Switch failed',
    errForbidden: 'the request was refused (loopback-trusted browsers only)',
    errBadMethod: 'the route refused this request method',
    errBadContentType: 'the route expects a JSON request',
    errBadRequest: 'the request was malformed',
    errDeviceUnknown: 'the device is not connected — run android_devices, or start an emulator with android_boot',
    errDeviceOffline: 'the device is not ready (adb reports it offline)',
    errDeviceUnauthorized: 'the device has not authorized this computer — allow USB debugging on the phone, then retry',
    errDeviceBusy: 'another device is streaming; pick it in the device list to switch',
    errStreamNotRunning: 'no stream is running for this device',
    errStreamFailed: 'the device stream failed to start',
    errTokenInvalid: 'the access link expired; refresh to get a new one',
    errScreenshotMissing: 'the screenshot file is gone',
    errFrameMissing: 'no frame captured yet — the device is warming up',
    errAdbUnavailable: 'adb is unavailable on this host — install the Android platform tools',
    errUnavailable: 'the device is unavailable',
  },
  zh: {
    android: 'Android 设备',
    actionBoot: '启动',
    actionScreenshot: '截图',
    actionInteract: '交互',
    actionBuildRun: '构建运行',
    booting: '正在启动设备画面…',
    connecting: '正在连接实时画面…',
    connectingScreenshot: '正在加载截图…',
    live: '实时',
    unavailable: '不可用',
    done: '完成',
    streamUnavailable: '画面不可用',
    screenshotUnavailable: '截图不可用',
    retry: '重试',
    refresh: '刷新',
    back: '返回',
    home: '主屏幕',
    recents: '最近任务',
    deviceMenu: '设备操作',
    deviceNotifications: '通知栏',
    deviceQuickSettings: '快捷设置',
    deviceLock: '锁屏',
    deviceWake: '唤醒',
    deviceAssistant: '语音助手',
    deviceActionFailed: '设备操作失败',
    screenshot: '截图',
    captured: '已截图',
    capturing: '正在截图…',
    rotate: '旋转',
    toolbar: '设备工具栏',
    sizeMode: '设备显示大小',
    frameStyle: '设备边框样式',
    frameStyleNone: '无框',
    frameStyleBezel: '边框',
    frameStyleDevice: '手机框',
    sizeQuickFit: '适应面板宽度',
    sizeQuickPercent100: '以 100% 显示',
    sizeQuickS: '小尺寸（S，240px）',
    sizeQuickM: '中尺寸（M，320px）',
    streamAlt: '实时 Android 画面 — 点击轻触，拖动手势',
    screenshotAlt: 'Android 设备截图',
    captureScreenshot: '正在截取屏幕…',
    interacting: '正在与设备交互…',
    building: '正在构建并安装应用…',
    noPreview: '此结果没有可用的实时视图。',
    toolFailed: '工具调用失败。',
    openApk: '打开 APK',
    openScreenshot: '打开截图',
    packageName: '包名',
    device: '设备',
    offline: '离线',
    panelLive: '实时',
    closePanel: '关闭设备面板',
    resizePanel: '拖动调整设备面板宽度',
    openInPanel: '在侧边栏打开',
    openAndroidPanel: '打开设备面板',
    devicePicker: 'Android 设备',
    deviceSwitching: '切换中…',
    deviceStreaming: '实时',
    deviceOnline: '在线',
    deviceEmulators: '模拟器',
    devicePhysical: '实体设备',
    deviceAvds: '可用 AVD',
    deviceAvdHint: '用 android_boot 启动',
    deviceNone: '未连接设备',
    followActive: '自动跟随',
    followHint: '面板自动跟随 agent 的最新目标设备',
    followResume: '恢复跟随',
    switchFailed: '切换失败',
    errForbidden: '请求被拒绝（仅限本机可信浏览器）',
    errBadMethod: '该路由不接受此请求方法',
    errBadContentType: '该路由需要 JSON 请求',
    errBadRequest: '请求格式不正确',
    errDeviceUnknown: '设备未连接——运行 android_devices，或用 android_boot 启动模拟器',
    errDeviceOffline: '设备尚未就绪（adb 报告为 offline）',
    errDeviceUnauthorized: '设备未授权这台电脑——请在手机上允许 USB 调试，然后重试',
    errDeviceBusy: '另一台设备正在推流；在设备列表里选择它即可切换',
    errStreamNotRunning: '该设备没有正在运行的画面流',
    errStreamFailed: '设备画面流启动失败',
    errTokenInvalid: '访问链接已过期，刷新即可重新获取',
    errScreenshotMissing: '截图文件已不存在',
    errFrameMissing: '尚未捕获画面——设备正在预热',
    errAdbUnavailable: '此主机没有可用的 adb——请安装 Android platform-tools',
    errUnavailable: '设备不可用',
  },
} as const

export type AndroidCopy = { readonly [Key in keyof typeof COPY.en]: string }

export function androidCopy(locale: string | undefined): AndroidCopy {
  return locale === 'zh' ? COPY.zh : COPY.en
}

/** Human-readable byte size for the screenshot caption. */
export function formatBytes(bytes: number | undefined): string | undefined {
  if (typeof bytes !== 'number' || !Number.isFinite(bytes) || bytes < 0) return undefined
  if (bytes < 1024) return `${bytes} B`
  return `${(bytes / 1024).toFixed(1)} KB`
}
